### ISSUE TITLE
Docker Container fails to start

### ISSUE THREAD

**Issue by Binternet** [pelias/interpolation#134]
I'm running some load testing on the pelias api docker and encountering these errors:

```
root@pelias-api:/pelias/dockerfiles# ./run_services.sh
Stopping pelias_api ... done
Stopping pelias_libpostal ... done
Stopping pelias_pip-service ... done
Stopping pelias_interpolation ... done
Removing pelias_libpostal_baseimage ... done
Removing pelias_libpostal ... done
Removing pelias_pip-service ... done
Removing pelias_interpolation ... done
Removing network dockerfiles_default
Removing network dockerfiles_pelias
ERROR: network dockerfiles_pelias has active endpoints
Creating network "dockerfiles_default" with the default driver
Creating pelias_interpolation

ERROR: for interpolation  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 113, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 56, in handle_connection_errors
    log_timeout_error()
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
```
This happens after the load testing, which usually causes even `docker ps` to hang...that requires me to restart the `docker` service.

**Comment by arthar360** [comment]
+1

**Comment by orangejulius** [comment]
This is probably fixed with the new http://github.com/pelias/docker/ repository, which is more robust than the old pelias/dockerfiles project. If anyone is still seeing this, let us know so we can try to figure out what the issue was.
