### ISSUE TITLE
Interpolation planet openaddresses data issue build without docker 

### ISSUE THREAD

**Issue by I1mran** [pelias/interpolation#229]
Hey team! 

I am building the planet without docker after the facing issue of difference in stats.
have noticed some errors after monitoring.

I have combined all CSV files into combine.csv with concat_oa.sh

command
```./interpolate oa address.db street.db < combine.csv```

---
#### First error while interpolation.
```
unable to project point on to linestring
street { id: 24954182,
  line: 'k|no_Ali~``F??',
  coordinates: [ [ -117.997223, 33.824726 ] ] }
point [ -118.012398, 33.8241002 ]
unable to project point on to linestring
street { id: 24954182,
  line: 'k|no_Ali~``F??',
  coordinates: [ [ -117.997223, 33.824726 ] ] }
point [ -118.0126581, 33.8241047 ]
unable to project point on to linestring
street { id: 24954182,
  line: 'k|no_Ali~``F??',
  coordinates: [ [ -117.997223, 33.824726 ] ] }
point [ -118.0129214, 33.8240954 ]
unable to project point on to linestring
street { id: 24954182,
  line: 'k|no_Ali~``F??',
  coordinates: [ [ -117.997223, 33.824726 ] ] }
point [ -118.0134353, 33.8240837 ]
unable to project point on to linestring
street { id: 24954182,
  line: 'k|no_Ali~``F??',
  coordinates: [ [ -117.997223, 33.824726 ] ] }
point [ -117.9949288, 33.8255711 ]
```

---
#### Second error while interpolation.

```invalid csv row Error: invalid house number
    at Address.setNumber (/home/pelias/interpolation/lib/Address.js:61:11)
    at DestroyableTransform._transform (/home/pelias/interpolation/stream/oa/convert.js:38:15)
    at DestroyableTransform.Transform._read (/home/pelias/interpolation/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Readable.read (/home/pelias/interpolation/node_modules/readable-stream/lib/_stream_readable.js:440:10)
    at flow (/home/pelias/interpolation/node_modules/readable-stream/lib/_stream_readable.js:920:34)
    at DestroyableTransform.pipeOnDrainFunctionResult (/home/pelias/interpolation/node_modules/readable-stream/lib/_stream_readable.js:730:7)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at onwriteDrain (/home/pelias/interpolation/node_modules/readable-stream/lib/_stream_writable.js:475:12)
    at afterWrite (/home/pelias/interpolation/node_modules/readable-stream/lib/_stream_writable.js:463:18)
{ LON: '-117.0811008',
  LAT: '33.6064783',
  NUMBER: '0',
  STREET: 'BANDOL DR',
  UNIT: '',
  CITY: 'WINCHESTER',
  DISTRICT: '',
  REGION: '',
  POSTCODE: '92596',
  ID: '',
  HASH: '/home/pelias/openaddresses/data/us/ca/riverside:009fbf363d01ca86' }
```

**Comment by I1mran** [comment]
https://github.com/pelias/docker/issues/141
